kind: Service
apiVersion: v1
metadata:
  name: express-server
  labels:
    app: express-server
spec:
  selector:
    app: express-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: express-server
  labels:
    app: express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
        - name: testk8s
          image: docker.io/pretorh/testk8s:first
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
